# Generated by Django 6.0.4 on 2026-05-02 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('spotify_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID de Spotify')),
                ('genres', models.JSONField(blank=True, default=list, verbose_name='Géneros')),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('tmdb_id', models.CharField(max_length=255, unique=True, verbose_name='ID de TMDb')),
                ('poster_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Póster')),
                ('synopsis', models.TextField(blank=True, verbose_name='Sinopsis')),
                ('genres', models.JSONField(blank=True, default=list, verbose_name='Géneros')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Lanzamiento')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('spotify_id', models.CharField(max_length=255, unique=True, verbose_name='ID de Spotify')),
                ('cover_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Portada')),
                ('genres', models.JSONField(blank=True, default=list, verbose_name='Géneros')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Lanzamiento')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='api.artist', verbose_name='Artista')),
            ],
            options={
                'verbose_name': 'Álbum',
                'verbose_name_plural': 'Álbumes',
            },
        ),
    ]
