# Generated by Django 6.0.4 on 2026-05-02 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_artist_movie_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Agregado por')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.album', verbose_name='Álbum')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='api.customgroup', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Álbum de Grupo',
                'verbose_name_plural': 'Álbumes de Grupos',
                'unique_together': {('group', 'album')},
            },
        ),
        migrations.CreateModel(
            name='GroupMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Agregado por')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='api.customgroup', verbose_name='Grupo')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.movie', verbose_name='Película')),
            ],
            options={
                'verbose_name': 'Película de Grupo',
                'verbose_name_plural': 'Películas de Grupos',
                'unique_together': {('group', 'movie')},
            },
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Calificación')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.album', verbose_name='Álbum')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.movie', verbose_name='Película')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reseña de Usuario',
                'verbose_name_plural': 'Reseñas de Usuarios',
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='rating_range'), models.CheckConstraint(condition=models.Q(models.Q(('album__isnull', False), ('movie__isnull', True)), models.Q(('album__isnull', True), ('movie__isnull', False)), _connector='OR'), name='review_target_exclusive')],
            },
        ),
    ]
